### ISSUE TITLE
-o cannot extract parse trees

### ISSUE THREAD

**Issue by panda2134** [muldvarp/CFGAnalyzer#1]
The help output says:
```
  --ambiguity 
    checks whether G1 is ambiguous
    an example will be a word w in L(G1) which has two parse trees (use -o to have parse trees extracted)
```

However `-o` is defined in `main.ml` to set the SAT Solver.

**Comment by muldvarp** [comment]
This is clearly just a typo. `./main.native --help` shows that the command line parameter for extracting parse trees is `-d`.
